version: '3.8'
services:
  app:
    build: weatherAPI
    environment:
      - LISTEN_PORT=${LISTEN_PORT}
      - API_URL=${API_URL}
      - GRPC_ADDR=${GRPC_ADDR}
      - GRPC_PORT=${GRPC_PORT}
      - REDIS_SERVER=${REDIS_SERVER}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_CLUSTER=${REDIS_CLUSTER}
    ports:
      - ${EXT_LISTEN_PORT}:${LISTEN_PORT}
  auth:
    build: weatherAUTH
    environment:
      - GRPC_PORT=${GRPC_PORT}
  prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      # - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090

