version: '3.8'
services:
  app:
    build: weatherAPI
    environment:
      - LISTEN_PORT=${LISTEN_PORT}
      - API_URL=${API_URL}
      - GRPC_ADDR=${GRPC_ADDR}
      - GRPC_PORT=${GRPC_PORT}
    ports:
      - ${EXT_LISTEN_PORT}:${LISTEN_PORT}
  auth:
    build: weatherAUTH
    environment:
      - GRPC_PORT=${GRPC_PORT}
