version: '3.8'
services:
  app:
    build: weatherAPI
    environment:
      - LISTEN_PORT=${LISTEN_PORT}
      - API_URL=${API_URL}
      - GRPC_ADDR=auth
      - GRPC_PORT=50051
    ports:
      - ${LISTEN_PORT}:${LISTEN_PORT}
  auth:
    build: weatherAUTH